version: "3.9"
services:
    build:
        image: cypress/browsers:node16.17.0-chrome106
        container_name: web-components-build
        command: sh web-components/ci/build.sh
        volumes:
            - ${HOME:-.}/.npmrc:/root/.npmrc:ro
            - ./..:/web-components
            - /web-components/node_modules

#    cypress-test:
#        image: cypress/base:16.17.1
#        container_name: web-components-cypress-test
#        command: sh web-components/ci/test.sh
#        volumes:
#            - ./..:/web-components
#            - /web-components/node_modules


    build	20-Oct-2022 11:14:26	[36mweb-components-build |[0m npm ERR! code ECONNRESET
    build	20-Oct-2022 11:14:26	[36mweb-components-build |[0m npm ERR! syscall read
    build	20-Oct-2022 11:14:26	[36mweb-components-build |[0m npm ERR! errno ECONNRESET
build	20-Oct-2022 11:14:26	[36mweb-components-build |[0m npm ERR! network Invalid response body while trying to fetch https://repo.omgeving.vlaanderen.be/artifactory/api/npm/acd-npm/node-fetch: read ECONNRESET
    build	20-Oct-2022 11:14:26	[36mweb-components-build |[0m npm ERR! network This is a problem related to network connectivity.
    build	20-Oct-2022 11:14:26	[36mweb-components-build |[0m npm ERR! network In most cases you are behind a proxy or have bad network settings.
    b
