name: build-applications-actions
on:
  push:
    paths:
      - applications/**
jobs:
  build-applications:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./applications
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Applications - npm ci
        run: npm ci
      - name: Applications - test
        run: npx nx test
      - name: Applications - build
        run: npx nx build
