name: ci-applications
on:
  push:
    paths:
      - .github/workflows/ci-applications.yml
      - applications/**
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  ci-applications:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./applications
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: authenticate to acd-npm repository
        run: |
          echo "registry=https://repo.omgeving.vlaanderen.be/artifactory/api/npm/acd-npm/"  > ~/.npmrc
          echo "//repo.omgeving.vlaanderen.be/artifactory/api/npm/acd-npm/:_authToken=${{ secrets.NPM_TOKEN_DOMG_ACD_NPM }}" >> ~/.npmrc
      - name: applications - npm ci
        run: npm ci
        continue-on-error: false
      - name: applications - test
        run: npx nx test
        continue-on-error: false
      - name: applications - build
        run: npx nx build
