name: ci-publish-npm-artifacts

on:
  workflow_dispatch:
    inputs:
      run-number:
        description: specify the run-number of the 'ci-web-components' workflow of which the libs will get published to local-npm of repo.omgeving.vlaanderen.be

jobs:
  ci-release-web-components:
    runs-on: ubuntu-latest
    outputs:
      build-results: https://github.com/milieuinfo/uig-pages/build/${{ github.ref_name }}/${{ github.workflow }}/${{ github.run_number }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: ./web-components
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci-web-components.yml
          run_number: ${{ github.event.inputs.run-number }}
          name: dist-build-apps-libs-and-storybook
      - name: authenticate to local-npm repository
        run: |
          echo "registry=https://repo.omgeving.vlaanderen.be/artifactory/api/npm/local-npm/"  > ~/.npmrc
          echo "//repo.omgeving.vlaanderen.be/artifactory/api/npm/local-npm/:_authToken=${{ secrets.NPM_TOKEN_DOMG }}" > ~/.npmrc
      - name: publish to npm
        run: |
          cd ./libs/common/utilities && npm version ${{ steps.package-version.outputs.current-version}} && npm publish
          cd ./libs/elements && npm version ${{ steps.package-version.outputs.current-version}} && npm publish
          cd ./libs/components && npm version ${{ steps.package-version.outputs.current-version}} && npm publish
          cd ./libs/sections && npm version ${{ steps.package-version.outputs.current-version}} && npm publish"
