name: ci-web-components
on:
  push:
    paths:
      - .github/workflows/ci-web-components.yml
      - web-components/**
jobs:
  ci-web-components:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web-components
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: web-components - npm ci
        run: npm ci
        continue-on-error: false
      - name: web-components - test
        run: npx nx test
        continue-on-error: false
      - name: web-components - build
        run: npx nx build
      - name: web-components - elements - build
        run: npx nx build elements
      - name: output the build results output path
        run: echo "the build results are available at build/${{ env.GITHUB_REF_NAME }}/${{ github.workflow }}/${{ env.GITHUB_RUN_ATTEMPT }}"
      - name: 🚀 publish dist folder on github-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-components/dist
          repository-name: milieuinfo/uig-pages
          target-folder: build/${{ env.GITHUB_REF_NAME }}/${{ github.workflow }}/${{ env.GITHUB_RUN_ATTEMPT }}

      # - name: authenticate to private NPM repository
      #   run: echo "//repo.omgeving.vlaanderen.be/artifactory/api/npm/local-npm/:_authToken=${{ secrets.NPM_TOKEN_DOMG }}" > ~/.npmrc
      # - name: web-components - elements - publish
      #  working-directory: ./web-components/dist/libs/elements
      #  run: npm run release
