name: ci-web-components
on:
  push:
    paths:
      - .github/workflows/ci-web-components.yml
      - web-components/**
jobs:
  ci-web-components:
    runs-on: ubuntu-latest
    outputs:
      build-results: https://github.com/milieuinfo/uig-pages/build/${{ github.ref_name }}/${{ github.workflow }}/${{ github.run_number }}
    defaults:
      run:
        shell: bash
        working-directory: ./web-components
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: web-components/package-lock.json
      # - name: delete lock file
      #  run: rm package-lock.json
      - name: authenticate to acd-npm repository
        run: |
          echo "registry=https://repo.omgeving.vlaanderen.be/artifactory/api/npm/acd-npm/"  > ~/.npmrc
          echo "//repo.omgeving.vlaanderen.be/artifactory/api/npm/acd-npm/:_authToken=${{ secrets.NPM_TOKEN_DOMG_ACD_NPM }}" >> ~/.npmrc
      - name: web-components - get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: ./web-components
      - name: web-components - npm install
        run: npm ci
        continue-on-error: false
      - name: web-components - test
        run: npx nx test
        continue-on-error: false
      - name: web-components - storybook - build
        run: npx nx build-storybook storybook
      - name: web-components - storybook - e2e-test
        run: npm run storybook:ci-test
      - name: web-components - build all
        run: npm run build:all
      - name: authenticate to local-npm repository
        run: |
          echo "registry=https://repo.omgeving.vlaanderen.be/artifactory/api/npm/local-npm/"  > ~/.npmrc
          echo "//repo.omgeving.vlaanderen.be/artifactory/api/npm/local-npm/:_authToken=${{ secrets.NPM_TOKEN_DOMG }}" > ~/.npmrc
      - name: web-components - release all
        run: npm run release:all
      - name: output the build result path
        run: echo "the build result (dist folder) is available at build-bamboo/web-components/${{ github.ref_name }}/${{ github.run_number }}"
      - name: 🚀 publish dist folder on github-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-components/dist
          repository-name: milieuinfo/uig-pages
          branch: main
          target-folder: build-bamboo/${{ github.ref_name }}/web-components/${{ github.run_number }}
          token: ${{ secrets.PAT_UIG_PAGES }}
      - name: publish Exhibit on github-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-components/dist/apps/exhibit
          repository-name: milieuinfo/uig-pages
          branch: main
          target-folder: /build-apps/${{ github.ref_name }}/${{ steps.package-version.outputs.current-version}}/exhibit
          token: ${{ secrets.PAT_UIG_PAGES }}
      - name: publish Storybook on github-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-components/dist/apps/storybook
          repository-name: milieuinfo/uig-pages
          branch: main
          target-folder: /build-apps/${{ github.ref_name }}/${{ steps.package-version.outputs.current-version}}/storybook
          token: ${{ secrets.PAT_UIG_PAGES }}
      - name: publish documentation on github-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation
          repository-name: milieuinfo/uig-pages
          branch: main
          target-folder: /build-apps/${{ github.ref_name }}/${{ steps.package-version.outputs.current-version}}/documentation
          token: ${{ secrets.PAT_UIG_PAGES }}
      # - name: web-components - elements - publish
      #  working-directory: ./web-components/dist/libs/elements
      #  run: npm run release
