name: ci-web-components
on:
  push:
    paths:
      - .github/workflows/ci-web-components.yml
      - web-components/**
jobs:
  ci-web-components:
    runs-on: ubuntu-latest
    outputs:
      build-results: https://github.com/milieuinfo/uig-pages/build/${{ github.ref_name }}/${{ github.workflow }}/${{ github.run_number }}
    defaults:
      run:
        shell: bash
        working-directory: ./web-components
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: web-components/package-lock.json
      # - name: delete lock file
      #  run: rm package-lock.json
      - name: authenticate to private NPM repository
        run: |
          echo "registry=https://repo.omgeving.vlaanderen.be/artifactory/api/npm/acd-npm/"  > ~/.npmrc
          echo "//repo.omgeving.vlaanderen.be/artifactory/api/npm/acd-npm/:_authToken=${{ secrets.NPM_TOKEN_DOMG_ACD_NPM }}" >> ~/.npmrc
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: web-components - npm install
        run: npm ci
        continue-on-error: false
      - name: web-components - test
        run: npx nx test
        continue-on-error: false
      - name: web-components - build
        run: npx nx build
      - name: web-components - common-utilities - build
        run: npx nx build common-utilities
      - name: web-components - elements - build
        run: npx nx build elements
      - name: web-components - components - build
        run: npx nx build components
      - name: web-components - storybook - e2e-test
        run: npm run storybook:ci-test
      - name: web-components - storybook - build
        run: npx nx build-storybook storybook
      #      - name: Archive dist folder
      #        uses: actions/upload-artifact@v3
      #        with:
      #          name: dist
      #          path: web-components/dist
      #      - name: Archive Exhibit
      #        uses: actions/upload-artifact@v3
      #        with:
      #          name: exhibit
      #          path: /web-components/dist/apps/exhibit
      #      - name: Archive Storybook
      #        uses: actions/upload-artifact@v3
      #        with:
      #          name: storybook
      #          path: /web-components/dist/apps/storybook
      - name: output the build results output path
        run: echo "the build results are available at build-bamboo/web-components/${{ github.ref_name }}/${{ github.run_number }}"
      - name: 🚀 publish dist folder on github-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-components/dist
          repository-name: milieuinfo/uig-pages
          branch: main
          target-folder: build-bamboo/web-components/${{ github.ref_name }}/${{ github.run_number }}
          token: ${{ secrets.PAT_UIG_PAGES }}
      - name: publish the Exhibit App on github-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-components/dist/apps/exhibit
          repository-name: milieuinfo/uig-pages
          branch: main
          target-folder: /build-apps/${{ steps.package-version.outputs.current-version}}/exhibit
          token: ${{ secrets.PAT_UIG_PAGES }}
      - name: publish Storybook on github-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-components/dist/apps/storybook
          repository-name: milieuinfo/uig-pages
          branch: main
          target-folder: /build-apps/${{ steps.package-version.outputs.current-version}}/storybook
          token: ${{ secrets.PAT_UIG_PAGES }}
      # - name: authenticate to private NPM repository
      #   run: echo "//repo.omgeving.vlaanderen.be/artifactory/api/npm/local-npm/:_authToken=${{ secrets.NPM_TOKEN_DOMG }}" > ~/.npmrc
      # - name: web-components - elements - publish
      #  working-directory: ./web-components/dist/libs/elements
      #  run: npm run release
