name: ci-web-components
on:
  push:
    paths:
      - .github/workflows/ci-web-components.yml
      - web-components/**
jobs:
  ci-web-components:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./web-components
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: web-components - npm ci
        run: npm ci
        continue-on-error: false
      - name: web-components - test
        run: npx nx test
        continue-on-error: false
      - name: web-components - build
        run: npx nx build
      - name: web-components - elements - build
        run: npx nx build elements
      - name: web-components - elements - publish
        uses: honzabilek4/npm-publish@v1.5.1
        with:
          registry: https://repo.omgeving.vlaanderen.be/artifactory/api/npm/local-npm/
          token: ${{ secrets.NPM_TOKEN_DOMG }}
          package: ./web-components/dist/libs/elements/package.json
          dry-run: true
